In [2]:
import pandas as pd

In [3]:
# Resultados obtenidos en los notebooks anteriores.
#
# MAE:
# Error promedio en dólares.
#
# RMSE:
# Error que penaliza más los errores grandes.
#
# R²:
# Porcentaje del comportamiento del precio que explica el modelo.

results = {
    "Modelo": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        17187.42,
        17422.17,
        16593.49
    ],
    "RMSE": [
        25718.39,
        29346.73,
        29894.17
    ],
    "R2": [
        0.9138,
        0.8877,
        0.8835
    ]
}

comparison_df = pd.DataFrame(results)

comparison_df

              Modelo       MAE      RMSE      R2
0  Linear Regression  17187.42  25718.39  0.9138
1      Random Forest  17422.17  29346.73  0.8877
2  Gradient Boosting  16593.49  29894.17  0.8835

In [ ]:
# Ordenamos por RMSE porque queremos priorizar
# el modelo que tenga menos errores grandes
#
# En precios de vivienda, los errores grandes
# pueden ser muy costosos

comparison_df.sort_values(
    by="RMSE",
    ascending=True
)

              Modelo       MAE      RMSE      R2
0  Linear Regression  17187.42  25718.39  0.9138
1      Random Forest  17422.17  29346.73  0.8877
2  Gradient Boosting  16593.49  29894.17  0.8835

In [ ]:
best_model = comparison_df.sort_values(
    by="RMSE",
    ascending=True
).iloc[0] #Tomar el primer modelo de la tabla ordenada

best_model

Modelo    Linear Regression
MAE                17187.42
RMSE               25718.39
R2                   0.9138
Name: 0, dtype: object

In [6]:
print("Modelo seleccionado:", best_model["Modelo"])
print(f"MAE : {best_model['MAE']:,.2f}")
print(f"RMSE: {best_model['RMSE']:,.2f}")
print(f"R²  : {best_model['R2']:.4f}")

Modelo seleccionado: Linear Regression
MAE : 17,187.42
RMSE: 25,718.39
R²  : 0.9138